#include "project_templates.hpp"
#include "project_manager.hpp"

#include <cctype>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <utility>
#include <vector>

namespace fs = std::filesystem;

namespace {

using FileMap = std::vector<std::pair<std::string, std::string>>;

bool ensure_dir(const std::string &path, std::string &error) {
  std::error_code ec;
  fs::create_directories(path, ec);
  if (ec) {
    error = "Failed to create directory: " + path + " (" + ec.message() + ")";
    return false;
  }
  return true;
}

bool write_tree(const std::string &root, const FileMap &files, std::string &error) {
  for (const auto &item : files) {
    const fs::path full = fs::path(root) / item.first;
    if (!ensure_dir(full.parent_path().string(), error))
      return false;
    std::ofstream out(full);
    if (!out) {
      error = "Failed to write file: " + full.string();
      return false;
    }
    out << item.second;
  }
  return true;
}

std::string app_id(const GabProjectInfo &info) {
  return "org.example." + GabProjectTemplates::sanitize_app_id(info.name);
}

std::string readme(const std::string &name, const std::string &blurb,
                   const std::string &hint) {
  return "# " + name + "\n\n" + blurb +
         "\n\nGenerated by **Luma Builder**.\n\n## Build\n\n```bash\n" + hint +
         "\n```\n";
}

std::string desktop(const GabProjectInfo &info) {
  return "[Desktop Entry]\nName=" + info.name + "\nExec=" + info.name +
         "\nIcon=" + info.name +
         "\nTerminal=false\nType=Application\nCategories=GNOME;GTK;\n";
}

std::string meson_exec(const GabProjectInfo &info, const std::string &lang,
                       const std::string &src, const std::vector<std::string> &deps) {
  std::ostringstream o;
  o << "project('" << info.name << "', '" << lang << "',\n"
    << "  version: '0.1.0',\n"
    << "  meson_version: '>= 1.0.0',\n"
    << "  default_options: ['warning_level=2', '"
    << (lang == "cpp" ? "cpp_std=c++17" : "c_std=c11") << "'],\n)\n\n";
  if (!deps.empty()) {
    o << "deps = [\n";
    for (const auto &d : deps)
      o << "  dependency('" << d << "'),\n";
    o << "]\n\nexecutable('" << info.name << "',\n  '" << src
      << "',\n  dependencies: deps,\n  install: true,\n)\n";
  } else {
    o << "executable('" << info.name << "', '" << src << "', install: true)\n";
  }
  return o.str();
}

std::string meson_hint(const GabProjectInfo &info) {
  return "meson setup build && meson compile -C build && ./build/" + info.name;
}

std::string cmake_hint(const GabProjectInfo &info) {
  return "cmake -S . -B build && cmake --build build && ./build/" + info.name;
}

void add_gui_meta(FileMap &files, const GabProjectInfo &info, const std::string &blurb) {
  files.emplace_back("data/" + info.name + ".desktop", desktop(info));
  files.emplace_back("README.md", readme(info.name, blurb, meson_hint(info)));
}

std::string main_c_wrap(const GabProjectInfo &info, bool adw, const std::string &extras,
                        const std::string &activate_body) {
  std::ostringstream o;
  o << (adw ? "#include <adwaita.h>\n" : "#include <gtk/gtk.h>\n") << extras << "\n"
    << "static void\nactivate (GtkApplication *app, gpointer user_data)\n{\n"
    << "  (void) user_data;\n"
    << activate_body << "}\n\n"
    << "int\nmain (int argc, char **argv)\n{\n";
  if (adw)
    o << "  AdwApplication *app = adw_application_new (\"" << app_id(info)
      << "\", G_APPLICATION_DEFAULT_FLAGS);\n";
  else
    o << "  GtkApplication *app = gtk_application_new (\"" << app_id(info)
      << "\", G_APPLICATION_DEFAULT_FLAGS);\n";
  o << "  g_signal_connect (app, \"activate\", G_CALLBACK (activate), NULL);\n"
    << "  return g_application_run (G_APPLICATION (app), argc, argv);\n}\n";
  return o.str();
}

std::string main_cpp_wrap(const GabProjectInfo &info, bool adw,
                          const std::string &activate_body) {
  std::ostringstream o;
  o << (adw ? "#include <adwaita.h>\n\n" : "#include <gtk/gtk.h>\n\n")
    << "static void activate(GtkApplication *app, gpointer) {\n"
    << activate_body << "}\n\n"
    << "int main(int argc, char **argv) {\n";
  if (adw)
    o << "  auto *app = adw_application_new(\"" << app_id(info)
      << "\", G_APPLICATION_DEFAULT_FLAGS);\n";
  else
    o << "  auto *app = gtk_application_new(\"" << app_id(info)
      << "\", G_APPLICATION_DEFAULT_FLAGS);\n";
  o << "  g_signal_connect(app, \"activate\", G_CALLBACK(activate), nullptr);\n"
    << "  return g_application_run(G_APPLICATION(app), argc, argv);\n}\n";
  return o.str();
}

} // namespace

std::string GabProjectTemplates::sanitize_app_id(const std::string &name) {
  std::string out;
  for (char c : name) {
    if (std::isalnum(static_cast<unsigned char>(c)))
      out.push_back(static_cast<char>(std::tolower(static_cast<unsigned char>(c))));
    else if (c == '-' || c == '_')
      out.push_back('_');
  }
  if (out.empty())
    out = "app";
  if (std::isdigit(static_cast<unsigned char>(out.front())))
    out = "app_" + out;
  return out;
}

std::string GabProjectTemplates::display_title(const GabTemplateMeta &meta) {
  return meta.category + " · " + meta.title;
}

std::vector<GabTemplateMeta> GabProjectTemplates::catalog() {
  return {
      {"gtk4-adwaita", "Hello Adwaita", "Simple libadwaita window", "GNOME"},
      {"gtk4", "Hello GTK4", "Minimal GTK4 window", "GTK"},
      {"gtk4-adwaita-cpp", "Hello Adwaita (C++)", "libadwaita in C++", "GNOME"},
      {"gtk4-cpp", "Hello GTK4 (C++)", "GTK4 window in C++", "GTK"},
      {"gtk4-headerbar", "Header Bar", "Header bar + menu button", "GTK"},
      {"gtk4-adwaita-navigation", "Navigation View", "Two-page AdwNavigationView", "GNOME"},
      {"gtk4-adwaita-preferences", "Preferences", "AdwPreferencesWindow sample", "GNOME"},
      {"gtk4-adwaita-toast", "Toast Overlay", "Show Adwaita toasts", "GNOME"},
      {"gtk4-adwaita-about", "About Dialog", "AdwAboutDialog + menu", "GNOME"},
      {"gtk4-adwaita-status", "Status Page", "AdwStatusPage empty state", "GNOME"},
      {"gtk4-adwaita-banner", "Banner", "AdwBanner message strip", "GNOME"},
      {"gtk4-listbox", "List Box", "GtkListBox with rows", "GTK"},
      {"gtk4-notebook", "Notebook Tabs", "GtkNotebook multi-tab", "GTK"},
      {"gtk4-stack", "Stack Switcher", "GtkStack + switcher", "GTK"},
      {"gtk4-paned", "Paned Split", "Horizontal GtkPaned", "GTK"},
      {"gtk4-drawing", "Drawing Area", "Cairo in GtkDrawingArea", "GTK"},
      {"gtk4-css", "Custom CSS", "CSS provider theming", "GTK"},
      {"gtk4-file-chooser", "File Chooser", "Open file dialog", "GTK"},
      {"gtk4-entry-form", "Entry Form", "Simple form + button", "GTK"},
      {"gtk4-shortcuts", "Shortcuts Window", "GtkShortcutsWindow", "GTK"},
      {"gtk4-sourceview", "Source Editor", "GtkSourceView 5 shell", "Editor"},
      {"gtk4-columnview", "Column View", "GtkColumnView list", "GTK"},
      {"gtk4-dnd", "Drag & Drop", "Accept dropped files", "GTK"},
      {"gtk4-grid", "Grid Layout", "GtkGrid of buttons", "GTK"},
      {"gtk4-progress", "Progress Bar", "Indeterminate progress", "GTK"},
      {"console-c", "Console (C)", "Hello world CLI", "Console"},
      {"console-cpp", "Console (C++)", "Hello world C++ CLI", "Console"},
      {"cli-goption", "CLI + GOption", "GLib option parsing", "Console"},
      {"shared-lib-c", "Shared Library (C)", "lib + demo executable", "Library"},
      {"static-lib-cpp", "Static Library (C++)", "Static lib + demo", "Library"},
      {"cmake-gtk4", "CMake GTK4", "GTK4 hello via CMake", "Build"},
      {"cmake-console-cpp", "CMake Console (C++)", "CMake C++ CLI", "Build"},
      {"empty-meson-c", "Empty Meson (C)", "Bare C skeleton", "Empty"},
      {"empty-meson-cpp", "Empty Meson (C++)", "Bare C++ skeleton", "Empty"},
      {"flatpak-adwaita", "Flatpak Adwaita", "Adwaita + Flatpak manifest", "Packaging"},
      {"python-gi", "Python GTK4", "PyGObject hello window", "Python"},
  };
}

const GabTemplateMeta *GabProjectTemplates::find(const std::string &id) {
  static const auto all = catalog();
  for (const auto &t : all) {
    if (t.id == id)
      return &t;
  }
  return nullptr;
}

bool GabProjectTemplates::generate(const GabProjectInfo &info, std::string &error) {
  const GabTemplateMeta *meta = find(info.template_id);
  const std::string tid = meta ? meta->id : "gtk4-adwaita";
  FileMap files;
  const std::string n = info.name;

  auto gtk_c = [&](bool adw, bool gsv, const std::string &extras, const std::string &body,
                   const std::string &blurb) {
    std::vector<std::string> deps = {"gtk4"};
    if (adw)
      deps.push_back("libadwaita-1");
    if (gsv)
      deps.push_back("gtksourceview-5");
    files.emplace_back("meson.build", meson_exec(info, "c", "src/main.c", deps));
    files.emplace_back("src/main.c", main_c_wrap(info, adw, extras, body));
    add_gui_meta(files, info, blurb);
  };

  auto gtk_cpp = [&](bool adw, const std::string &body, const std::string &blurb) {
    std::vector<std::string> deps = {"gtk4"};
    if (adw)
      deps.push_back("libadwaita-1");
    files.emplace_back("meson.build", meson_exec(info, "cpp", "src/main.cpp", deps));
    files.emplace_back("src/main.cpp", main_cpp_wrap(info, adw, body));
    add_gui_meta(files, info, blurb);
  };

  if (tid == "gtk4-adwaita" || tid == "flatpak-adwaita") {
    gtk_c(true, false, "",
          "  GtkWidget *window = adw_application_window_new (app);\n"
          "  gtk_window_set_title (GTK_WINDOW (window), \"" +
              n +
              "\");\n"
              "  gtk_window_set_default_size (GTK_WINDOW (window), 640, 480);\n"
              "  adw_application_window_set_content (ADW_APPLICATION_WINDOW (window),\n"
              "      gtk_label_new (\"Hello from " +
              n +
              "!\"));\n"
              "  gtk_window_present (GTK_WINDOW (window));\n",
          "A libadwaita GTK4 application.");
    if (tid == "flatpak-adwaita") {
      files.emplace_back(
          "flatpak/" + app_id(info) + ".yml",
          "app-id: " + app_id(info) +
              "\nruntime: org.gnome.Platform\nruntime-version: '46'\nsdk: org.gnome.Sdk\n"
              "command: " +
              n +
              "\nfinish-args:\n  - --share=ipc\n  - --socket=fallback-x11\n"
              "  - --socket=wayland\n  - --device=dri\nmodules:\n  - name: " +
              n +
              "\n    buildsystem: meson\n    sources:\n      - type: dir\n        path: ..\n");
    }
  } else if (tid == "gtk4") {
    gtk_c(false, false, "",
          "  GtkWidget *window = gtk_application_window_new (app);\n"
          "  gtk_window_set_title (GTK_WINDOW (window), \"" +
              n +
              "\");\n"
              "  gtk_window_set_default_size (GTK_WINDOW (window), 640, 480);\n"
              "  gtk_window_set_child (GTK_WINDOW (window), gtk_label_new (\"Hello from " +
              n +
              "!\"));\n"
              "  gtk_window_present (GTK_WINDOW (window));\n",
          "A minimal GTK4 application.");
  } else if (tid == "gtk4-adwaita-cpp") {
    gtk_cpp(true,
            "  auto *window = adw_application_window_new(app);\n"
            "  gtk_window_set_title(GTK_WINDOW(window), \"" +
                n +
                "\");\n"
                "  gtk_window_set_default_size(GTK_WINDOW(window), 640, 480);\n"
                "  adw_application_window_set_content(ADW_APPLICATION_WINDOW(window),\n"
                "      gtk_label_new(\"Hello from " +
                n +
                "!\"));\n"
                "  gtk_window_present(GTK_WINDOW(window));\n",
            "libadwaita hello world in C++.");
  } else if (tid == "gtk4-cpp") {
    gtk_cpp(false,
            "  auto *window = gtk_application_window_new(app);\n"
            "  gtk_window_set_title(GTK_WINDOW(window), \"" +
                n +
                "\");\n"
                "  gtk_window_set_default_size(GTK_WINDOW(window), 640, 480);\n"
                "  gtk_window_set_child(GTK_WINDOW(window), gtk_label_new(\"Hello from " +
                n +
                "!\"));\n"
                "  gtk_window_present(GTK_WINDOW(window));\n",
            "GTK4 hello world in C++.");
  } else if (tid == "gtk4-headerbar") {
    gtk_c(false, false, "",
          "  GtkWidget *window = gtk_application_window_new (app);\n"
          "  gtk_window_set_title (GTK_WINDOW (window), \"" +
              n +
              "\");\n"
              "  gtk_window_set_default_size (GTK_WINDOW (window), 720, 480);\n"
              "  GtkWidget *header = gtk_header_bar_new ();\n"
              "  gtk_window_set_titlebar (GTK_WINDOW (window), header);\n"
              "  GMenu *menu = g_menu_new ();\n"
              "  g_menu_append (menu, \"Quit\", \"app.quit\");\n"
              "  GtkWidget *btn = gtk_menu_button_new ();\n"
              "  gtk_menu_button_set_icon_name (GTK_MENU_BUTTON (btn), \"open-menu-symbolic\");\n"
              "  gtk_menu_button_set_menu_model (GTK_MENU_BUTTON (btn), G_MENU_MODEL (menu));\n"
              "  gtk_header_bar_pack_end (GTK_HEADER_BAR (header), btn);\n"
              "  gtk_window_set_child (GTK_WINDOW (window), gtk_label_new (\"Header bar template\"));\n"
              "  gtk_window_present (GTK_WINDOW (window));\n",
          "GTK4 app with header bar and menu.");
  } else if (tid == "gtk4-adwaita-navigation") {
    files.emplace_back("meson.build",
                       meson_exec(info, "c", "src/main.c", {"gtk4", "libadwaita-1"}));
    files.emplace_back(
        "src/main.c",
        "#include <adwaita.h>\n\n"
        "static void\non_open_detail (GtkButton *btn, gpointer user_data)\n{\n"
        "  (void) btn;\n"
        "  adw_navigation_view_push_by_tag (ADW_NAVIGATION_VIEW (user_data), \"detail\");\n"
        "}\n\n"
        "static void\nactivate (GtkApplication *app, gpointer user_data)\n{\n"
        "  (void) user_data;\n"
        "  GtkWidget *window = adw_application_window_new (app);\n"
        "  gtk_window_set_default_size (GTK_WINDOW (window), 720, 520);\n"
        "  GtkWidget *nav = adw_navigation_view_new ();\n"
        "  GtkWidget *home_box = gtk_box_new (GTK_ORIENTATION_VERTICAL, 12);\n"
        "  gtk_widget_set_valign (home_box, GTK_ALIGN_CENTER);\n"
        "  gtk_box_append (GTK_BOX (home_box), gtk_label_new (\"Home\"));\n"
        "  GtkWidget *open_btn = gtk_button_new_with_label (\"Open detail\");\n"
        "  gtk_box_append (GTK_BOX (home_box), open_btn);\n"
        "  AdwNavigationPage *home = adw_navigation_page_new (home_box, \"Home\");\n"
        "  adw_navigation_page_set_tag (home, \"home\");\n"
        "  AdwNavigationPage *detail = adw_navigation_page_new (gtk_label_new (\"Detail\"), \"Detail\");\n"
        "  adw_navigation_page_set_tag (detail, \"detail\");\n"
        "  adw_navigation_view_add (ADW_NAVIGATION_VIEW (nav), home);\n"
        "  adw_navigation_view_add (ADW_NAVIGATION_VIEW (nav), detail);\n"
        "  g_signal_connect (open_btn, \"clicked\", G_CALLBACK (on_open_detail), nav);\n"
        "  adw_application_window_set_content (ADW_APPLICATION_WINDOW (window), nav);\n"
        "  gtk_window_present (GTK_WINDOW (window));\n"
        "}\n\n"
        "int\nmain (int argc, char **argv)\n{\n"
        "  AdwApplication *app = adw_application_new (\"" +
            app_id(info) +
            "\", G_APPLICATION_DEFAULT_FLAGS);\n"
            "  g_signal_connect (app, \"activate\", G_CALLBACK (activate), NULL);\n"
            "  return g_application_run (G_APPLICATION (app), argc, argv);\n"
            "}\n");
    add_gui_meta(files, info, "AdwNavigationView two-page sample.");
  } else if (tid == "gtk4-adwaita-preferences") {
    gtk_c(true, false, "",
          "  GtkWidget *window = adw_preferences_window_new ();\n"
          "  gtk_window_set_application (GTK_WINDOW (window), app);\n"
          "  gtk_window_set_title (GTK_WINDOW (window), \"" +
              n +
              "\");\n"
              "  AdwPreferencesPage *page = adw_preferences_page_new ();\n"
              "  adw_preferences_page_set_title (page, \"General\");\n"
              "  AdwPreferencesGroup *group = adw_preferences_group_new ();\n"
              "  adw_preferences_group_set_title (group, \"Options\");\n"
              "  GtkWidget *row = adw_switch_row_new ();\n"
              "  adw_preferences_row_set_title (ADW_PREFERENCES_ROW (row), \"Enable feature\");\n"
              "  adw_preferences_group_add (group, row);\n"
              "  adw_preferences_page_add (page, group);\n"
              "  adw_preferences_window_add (ADW_PREFERENCES_WINDOW (window), page);\n"
              "  gtk_window_present (GTK_WINDOW (window));\n",
          "AdwPreferencesWindow starter.");
  } else if (tid == "gtk4-adwaita-toast") {
    files.emplace_back("meson.build",
                       meson_exec(info, "c", "src/main.c", {"gtk4", "libadwaita-1"}));
    files.emplace_back(
        "src/main.c",
        "#include <adwaita.h>\n\n"
        "static void\non_toast (GtkButton *btn, gpointer user_data)\n{\n"
        "  (void) btn;\n"
        "  adw_toast_overlay_add_toast (ADW_TOAST_OVERLAY (user_data),\n"
        "                              adw_toast_new (\"Hello from Luma!\"));\n"
        "}\n\n"
        "static void\nactivate (GtkApplication *app, gpointer user_data)\n{\n"
        "  (void) user_data;\n"
        "  GtkWidget *window = adw_application_window_new (app);\n"
        "  gtk_window_set_title (GTK_WINDOW (window), \"" +
            n +
            "\");\n"
            "  gtk_window_set_default_size (GTK_WINDOW (window), 480, 320);\n"
            "  GtkWidget *overlay = adw_toast_overlay_new ();\n"
            "  GtkWidget *btn = gtk_button_new_with_label (\"Show toast\");\n"
            "  gtk_widget_set_halign (btn, GTK_ALIGN_CENTER);\n"
            "  gtk_widget_set_valign (btn, GTK_ALIGN_CENTER);\n"
            "  adw_toast_overlay_set_child (ADW_TOAST_OVERLAY (overlay), btn);\n"
            "  g_signal_connect (btn, \"clicked\", G_CALLBACK (on_toast), overlay);\n"
            "  adw_application_window_set_content (ADW_APPLICATION_WINDOW (window), overlay);\n"
            "  gtk_window_present (GTK_WINDOW (window));\n"
            "}\n\n"
            "int\nmain (int argc, char **argv)\n{\n"
            "  AdwApplication *app = adw_application_new (\"" +
            app_id(info) +
            "\", G_APPLICATION_DEFAULT_FLAGS);\n"
            "  g_signal_connect (app, \"activate\", G_CALLBACK (activate), NULL);\n"
            "  return g_application_run (G_APPLICATION (app), argc, argv);\n"
            "}\n");
    add_gui_meta(files, info, "Adwaita toast overlay sample.");
  } else if (tid == "gtk4-adwaita-about") {
    files.emplace_back("meson.build",
                       meson_exec(info, "c", "src/main.c", {"gtk4", "libadwaita-1"}));
    files.emplace_back(
        "src/main.c",
        "#include <adwaita.h>\n\n"
        "static void\non_about (GSimpleAction *a, GVariant *p, gpointer window)\n{\n"
        "  (void) a; (void) p;\n"
        "  AdwDialog *about = adw_about_dialog_new ();\n"
        "  adw_about_dialog_set_application_name (ADW_ABOUT_DIALOG (about), \"" +
            n +
            "\");\n"
            "  adw_about_dialog_set_version (ADW_ABOUT_DIALOG (about), \"0.1.0\");\n"
            "  adw_about_dialog_set_developer_name (ADW_ABOUT_DIALOG (about), \"You\");\n"
            "  adw_dialog_present (about, GTK_WIDGET (window));\n"
            "}\n\n"
            "static void\nactivate (GtkApplication *app, gpointer user_data)\n{\n"
            "  (void) user_data;\n"
            "  GtkWidget *window = adw_application_window_new (app);\n"
            "  gtk_window_set_title (GTK_WINDOW (window), \"" +
            n +
            "\");\n"
            "  gtk_window_set_default_size (GTK_WINDOW (window), 480, 320);\n"
            "  const GActionEntry entries[] = {{ \"about\", on_about }};\n"
            "  g_action_map_add_action_entries (G_ACTION_MAP (window), entries, 1, window);\n"
            "  GtkWidget *btn = gtk_button_new_with_label (\"About\");\n"
            "  gtk_widget_set_halign (btn, GTK_ALIGN_CENTER);\n"
            "  gtk_widget_set_valign (btn, GTK_ALIGN_CENTER);\n"
            "  gtk_actionable_set_action_name (GTK_ACTIONABLE (btn), \"win.about\");\n"
            "  adw_application_window_set_content (ADW_APPLICATION_WINDOW (window), btn);\n"
            "  gtk_window_present (GTK_WINDOW (window));\n"
            "}\n\n"
            "int\nmain (int argc, char **argv)\n{\n"
            "  AdwApplication *app = adw_application_new (\"" +
            app_id(info) +
            "\", G_APPLICATION_DEFAULT_FLAGS);\n"
            "  g_signal_connect (app, \"activate\", G_CALLBACK (activate), NULL);\n"
            "  return g_application_run (G_APPLICATION (app), argc, argv);\n"
            "}\n");
    add_gui_meta(files, info, "AdwAboutDialog sample.");
  } else if (tid == "gtk4-adwaita-status") {
    gtk_c(true, false, "",
          "  GtkWidget *window = adw_application_window_new (app);\n"
          "  gtk_window_set_title (GTK_WINDOW (window), \"" +
              n +
              "\");\n"
              "  gtk_window_set_default_size (GTK_WINDOW (window), 560, 400);\n"
              "  GtkWidget *status = adw_status_page_new ();\n"
              "  adw_status_page_set_icon_name (ADW_STATUS_PAGE (status), \"folder-symbolic\");\n"
              "  adw_status_page_set_title (ADW_STATUS_PAGE (status), \"Nothing here yet\");\n"
              "  adw_status_page_set_description (ADW_STATUS_PAGE (status), \"Create something new.\");\n"
              "  adw_application_window_set_content (ADW_APPLICATION_WINDOW (window), status);\n"
              "  gtk_window_present (GTK_WINDOW (window));\n",
          "AdwStatusPage empty-state sample.");
  } else if (tid == "gtk4-adwaita-banner") {
    gtk_c(true, false, "",
          "  GtkWidget *window = adw_application_window_new (app);\n"
          "  gtk_window_set_title (GTK_WINDOW (window), \"" +
              n +
              "\");\n"
              "  gtk_window_set_default_size (GTK_WINDOW (window), 560, 360);\n"
              "  GtkWidget *box = gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);\n"
              "  GtkWidget *banner = adw_banner_new (\"Welcome to " +
              n +
              "\");\n"
              "  adw_banner_set_revealed (ADW_BANNER (banner), TRUE);\n"
              "  gtk_box_append (GTK_BOX (box), banner);\n"
              "  gtk_box_append (GTK_BOX (box), gtk_label_new (\"Main content\"));\n"
              "  adw_application_window_set_content (ADW_APPLICATION_WINDOW (window), box);\n"
              "  gtk_window_present (GTK_WINDOW (window));\n",
          "AdwBanner message strip sample.");
  } else if (tid == "gtk4-listbox") {
    gtk_c(false, false, "",
          "  GtkWidget *window = gtk_application_window_new (app);\n"
          "  gtk_window_set_title (GTK_WINDOW (window), \"" +
              n +
              "\");\n"
              "  gtk_window_set_default_size (GTK_WINDOW (window), 420, 480);\n"
              "  GtkWidget *list = gtk_list_box_new ();\n"
              "  const char *items[] = { \"Alpha\", \"Bravo\", \"Charlie\", NULL };\n"
              "  for (int i = 0; items[i]; i++)\n"
              "    gtk_list_box_append (GTK_LIST_BOX (list), gtk_label_new (items[i]));\n"
              "  GtkWidget *scroll = gtk_scrolled_window_new ();\n"
              "  gtk_scrolled_window_set_child (GTK_SCROLLED_WINDOW (scroll), list);\n"
              "  gtk_window_set_child (GTK_WINDOW (window), scroll);\n"
              "  gtk_window_present (GTK_WINDOW (window));\n",
          "GtkListBox sample.");
  } else if (tid == "gtk4-notebook") {
    gtk_c(false, false, "",
          "  GtkWidget *window = gtk_application_window_new (app);\n"
          "  gtk_window_set_title (GTK_WINDOW (window), \"" +
              n +
              "\");\n"
              "  gtk_window_set_default_size (GTK_WINDOW (window), 560, 400);\n"
              "  GtkWidget *nb = gtk_notebook_new ();\n"
              "  gtk_notebook_append_page (GTK_NOTEBOOK (nb), gtk_label_new (\"One\"), gtk_label_new (\"Tab 1\"));\n"
              "  gtk_notebook_append_page (GTK_NOTEBOOK (nb), gtk_label_new (\"Two\"), gtk_label_new (\"Tab 2\"));\n"
              "  gtk_notebook_append_page (GTK_NOTEBOOK (nb), gtk_label_new (\"Three\"), gtk_label_new (\"Tab 3\"));\n"
              "  gtk_window_set_child (GTK_WINDOW (window), nb);\n"
              "  gtk_window_present (GTK_WINDOW (window));\n",
          "GtkNotebook tabs sample.");
  } else if (tid == "gtk4-stack") {
    gtk_c(false, false, "",
          "  GtkWidget *window = gtk_application_window_new (app);\n"
          "  gtk_window_set_title (GTK_WINDOW (window), \"" +
              n +
              "\");\n"
              "  gtk_window_set_default_size (GTK_WINDOW (window), 480, 360);\n"
              "  GtkWidget *box = gtk_box_new (GTK_ORIENTATION_VERTICAL, 8);\n"
              "  GtkWidget *stack = gtk_stack_new ();\n"
              "  gtk_stack_add_titled (GTK_STACK (stack), gtk_label_new (\"Page A\"), \"a\", \"Page A\");\n"
              "  gtk_stack_add_titled (GTK_STACK (stack), gtk_label_new (\"Page B\"), \"b\", \"Page B\");\n"
              "  GtkWidget *switcher = gtk_stack_switcher_new ();\n"
              "  gtk_stack_switcher_set_stack (GTK_STACK_SWITCHER (switcher), GTK_STACK (stack));\n"
              "  gtk_box_append (GTK_BOX (box), switcher);\n"
              "  gtk_widget_set_vexpand (stack, TRUE);\n"
              "  gtk_box_append (GTK_BOX (box), stack);\n"
              "  gtk_window_set_child (GTK_WINDOW (window), box);\n"
              "  gtk_window_present (GTK_WINDOW (window));\n",
          "GtkStack with switcher.");
  } else if (tid == "gtk4-paned") {
    gtk_c(false, false, "",
          "  GtkWidget *window = gtk_application_window_new (app);\n"
          "  gtk_window_set_title (GTK_WINDOW (window), \"" +
              n +
              "\");\n"
              "  gtk_window_set_default_size (GTK_WINDOW (window), 720, 480);\n"
              "  GtkWidget *paned = gtk_paned_new (GTK_ORIENTATION_HORIZONTAL);\n"
              "  gtk_paned_set_start_child (GTK_PANED (paned), gtk_label_new (\"Sidebar\"));\n"
              "  gtk_paned_set_end_child (GTK_PANED (paned), gtk_label_new (\"Content\"));\n"
              "  gtk_paned_set_position (GTK_PANED (paned), 200);\n"
              "  gtk_window_set_child (GTK_WINDOW (window), paned);\n"
              "  gtk_window_present (GTK_WINDOW (window));\n",
          "GtkPaned split layout.");
  } else if (tid == "gtk4-drawing") {
    files.emplace_back("meson.build", meson_exec(info, "c", "src/main.c", {"gtk4"}));
    files.emplace_back(
        "src/main.c",
        "#include <gtk/gtk.h>\n\n"
        "static void\ndraw_cb (GtkDrawingArea *area, cairo_t *cr, int w, int h, gpointer data)\n{\n"
        "  (void) area; (void) data;\n"
        "  cairo_set_source_rgb (cr, 0.15, 0.45, 0.85);\n"
        "  cairo_arc (cr, w / 2.0, h / 2.0, MIN (w, h) / 3.0, 0, 2 * G_PI);\n"
        "  cairo_fill (cr);\n"
        "}\n\n"
        "static void\nactivate (GtkApplication *app, gpointer user_data)\n{\n"
        "  (void) user_data;\n"
        "  GtkWidget *window = gtk_application_window_new (app);\n"
        "  gtk_window_set_title (GTK_WINDOW (window), \"" +
            n +
            "\");\n"
            "  gtk_window_set_default_size (GTK_WINDOW (window), 480, 360);\n"
            "  GtkWidget *area = gtk_drawing_area_new ();\n"
            "  gtk_drawing_area_set_draw_func (GTK_DRAWING_AREA (area), draw_cb, NULL, NULL);\n"
            "  gtk_window_set_child (GTK_WINDOW (window), area);\n"
            "  gtk_window_present (GTK_WINDOW (window));\n"
            "}\n\n"
            "int\nmain (int argc, char **argv)\n{\n"
            "  GtkApplication *app = gtk_application_new (\"" +
            app_id(info) +
            "\", G_APPLICATION_DEFAULT_FLAGS);\n"
            "  g_signal_connect (app, \"activate\", G_CALLBACK (activate), NULL);\n"
            "  return g_application_run (G_APPLICATION (app), argc, argv);\n"
            "}\n");
    add_gui_meta(files, info, "Cairo drawing area sample.");
  } else if (tid == "gtk4-css") {
    gtk_c(false, false, "",
          "  GtkWidget *window = gtk_application_window_new (app);\n"
          "  gtk_window_set_title (GTK_WINDOW (window), \"" +
              n +
              "\");\n"
              "  gtk_window_set_default_size (GTK_WINDOW (window), 480, 320);\n"
              "  GtkCssProvider *provider = gtk_css_provider_new ();\n"
              "  gtk_css_provider_load_from_string (provider,\n"
              "      \"label.hero { font-size: 28pt; color: #1a5fb4; }\");\n"
              "  gtk_style_context_add_provider_for_display (gdk_display_get_default (),\n"
              "      GTK_STYLE_PROVIDER (provider), GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);\n"
              "  GtkWidget *label = gtk_label_new (\"Styled with CSS\");\n"
              "  gtk_widget_add_css_class (label, \"hero\");\n"
              "  gtk_window_set_child (GTK_WINDOW (window), label);\n"
              "  gtk_window_present (GTK_WINDOW (window));\n",
          "Custom CSS theming sample.");
  } else if (tid == "gtk4-file-chooser") {
    files.emplace_back("meson.build", meson_exec(info, "c", "src/main.c", {"gtk4"}));
    files.emplace_back(
        "src/main.c",
        "#include <gtk/gtk.h>\n\n"
        "static void\non_open_done (GObject *source, GAsyncResult *res, gpointer label)\n{\n"
        "  g_autoptr (GError) error = NULL;\n"
        "  g_autoptr (GFile) file = gtk_file_dialog_open_finish (GTK_FILE_DIALOG (source), res, &error);\n"
        "  if (file)\n"
        "    {\n"
        "      g_autofree char *path = g_file_get_path (file);\n"
        "      gtk_label_set_text (GTK_LABEL (label), path ? path : \"(no path)\");\n"
        "    }\n"
        "}\n\n"
        "static void\non_open (GtkButton *btn, gpointer user_data)\n{\n"
        "  GtkWidget *window = GTK_WIDGET (g_object_get_data (G_OBJECT (btn), \"window\"));\n"
        "  GtkFileDialog *dialog = gtk_file_dialog_new ();\n"
        "  gtk_file_dialog_open (dialog, GTK_WINDOW (window), NULL, on_open_done, user_data);\n"
        "}\n\n"
        "static void\nactivate (GtkApplication *app, gpointer user_data)\n{\n"
        "  (void) user_data;\n"
        "  GtkWidget *window = gtk_application_window_new (app);\n"
        "  gtk_window_set_title (GTK_WINDOW (window), \"" +
            n +
            "\");\n"
            "  gtk_window_set_default_size (GTK_WINDOW (window), 520, 240);\n"
            "  GtkWidget *box = gtk_box_new (GTK_ORIENTATION_VERTICAL, 12);\n"
            "  gtk_widget_set_valign (box, GTK_ALIGN_CENTER);\n"
            "  GtkWidget *label = gtk_label_new (\"No file selected\");\n"
            "  GtkWidget *btn = gtk_button_new_with_label (\"Open file…\");\n"
            "  g_object_set_data (G_OBJECT (btn), \"window\", window);\n"
            "  g_signal_connect (btn, \"clicked\", G_CALLBACK (on_open), label);\n"
            "  gtk_box_append (GTK_BOX (box), btn);\n"
            "  gtk_box_append (GTK_BOX (box), label);\n"
            "  gtk_window_set_child (GTK_WINDOW (window), box);\n"
            "  gtk_window_present (GTK_WINDOW (window));\n"
            "}\n\n"
            "int\nmain (int argc, char **argv)\n{\n"
            "  GtkApplication *app = gtk_application_new (\"" +
            app_id(info) +
            "\", G_APPLICATION_DEFAULT_FLAGS);\n"
            "  g_signal_connect (app, \"activate\", G_CALLBACK (activate), NULL);\n"
            "  return g_application_run (G_APPLICATION (app), argc, argv);\n"
            "}\n");
    add_gui_meta(files, info, "File open dialog sample.");
  } else if (tid == "gtk4-entry-form") {
    files.emplace_back("meson.build", meson_exec(info, "c", "src/main.c", {"gtk4"}));
    files.emplace_back(
        "src/main.c",
        "#include <gtk/gtk.h>\n\n"
        "static void\non_submit (GtkButton *btn, gpointer user_data)\n{\n"
        "  (void) btn;\n"
        "  GtkWidget **widgets = user_data;\n"
        "  const char *name = gtk_editable_get_text (GTK_EDITABLE (widgets[0]));\n"
        "  g_autofree char *msg = g_strdup_printf (\"Hello, %s!\", name && *name ? name : \"friend\");\n"
        "  gtk_label_set_text (GTK_LABEL (widgets[1]), msg);\n"
        "}\n\n"
        "static void\nactivate (GtkApplication *app, gpointer user_data)\n{\n"
        "  (void) user_data;\n"
        "  GtkWidget *window = gtk_application_window_new (app);\n"
        "  gtk_window_set_title (GTK_WINDOW (window), \"" +
            n +
            "\");\n"
            "  gtk_window_set_default_size (GTK_WINDOW (window), 420, 260);\n"
            "  GtkWidget *box = gtk_box_new (GTK_ORIENTATION_VERTICAL, 10);\n"
            "  gtk_widget_set_margin_start (box, 24);\n"
            "  gtk_widget_set_margin_end (box, 24);\n"
            "  gtk_widget_set_margin_top (box, 24);\n"
            "  GtkWidget *entry = gtk_entry_new ();\n"
            "  gtk_entry_set_placeholder_text (GTK_ENTRY (entry), \"Your name\");\n"
            "  GtkWidget *status = gtk_label_new (\"\");\n"
            "  GtkWidget *btn = gtk_button_new_with_label (\"Submit\");\n"
            "  static GtkWidget *pair[2];\n"
            "  pair[0] = entry; pair[1] = status;\n"
            "  g_signal_connect (btn, \"clicked\", G_CALLBACK (on_submit), pair);\n"
            "  gtk_box_append (GTK_BOX (box), entry);\n"
            "  gtk_box_append (GTK_BOX (box), btn);\n"
            "  gtk_box_append (GTK_BOX (box), status);\n"
            "  gtk_window_set_child (GTK_WINDOW (window), box);\n"
            "  gtk_window_present (GTK_WINDOW (window));\n"
            "}\n\n"
            "int\nmain (int argc, char **argv)\n{\n"
            "  GtkApplication *app = gtk_application_new (\"" +
            app_id(info) +
            "\", G_APPLICATION_DEFAULT_FLAGS);\n"
            "  g_signal_connect (app, \"activate\", G_CALLBACK (activate), NULL);\n"
            "  return g_application_run (G_APPLICATION (app), argc, argv);\n"
            "}\n");
    add_gui_meta(files, info, "Simple entry form sample.");
  } else if (tid == "gtk4-shortcuts") {
    files.emplace_back("meson.build", meson_exec(info, "c", "src/main.c", {"gtk4"}));
    files.emplace_back(
        "src/main.c",
        "#include <gtk/gtk.h>\n\n"
        "static void\non_shortcuts (GtkButton *btn, gpointer window)\n{\n"
        "  (void) btn;\n"
        "  GtkBuilder *builder = gtk_builder_new_from_string (\n"
        "      \"<?xml version='1.0'?>\"\n"
        "      \"<interface><object class='GtkShortcutsWindow' id='win'>\"\n"
        "      \"<property name='modal'>true</property>\"\n"
        "      \"<child><object class='GtkShortcutsSection'>\"\n"
        "      \"<child><object class='GtkShortcutsGroup'>\"\n"
        "      \"<property name='title'>General</property>\"\n"
        "      \"<child><object class='GtkShortcutsShortcut'>\"\n"
        "      \"<property name='title'>Quit</property>\"\n"
        "      \"<property name='accelerator'>&lt;primary&gt;q</property>\"\n"
        "      \"</object></child></object></child></object></child></object></interface>\", -1);\n"
        "  GtkWidget *sw = GTK_WIDGET (gtk_builder_get_object (builder, \"win\"));\n"
        "  gtk_window_set_transient_for (GTK_WINDOW (sw), GTK_WINDOW (window));\n"
        "  gtk_window_present (GTK_WINDOW (sw));\n"
        "  g_object_unref (builder);\n"
        "}\n\n"
        "static void\nactivate (GtkApplication *app, gpointer user_data)\n{\n"
        "  (void) user_data;\n"
        "  GtkWidget *window = gtk_application_window_new (app);\n"
        "  gtk_window_set_title (GTK_WINDOW (window), \"" +
            n +
            "\");\n"
            "  GtkWidget *btn = gtk_button_new_with_label (\"Show shortcuts\");\n"
            "  gtk_widget_set_halign (btn, GTK_ALIGN_CENTER);\n"
            "  gtk_widget_set_valign (btn, GTK_ALIGN_CENTER);\n"
            "  g_signal_connect (btn, \"clicked\", G_CALLBACK (on_shortcuts), window);\n"
            "  gtk_window_set_child (GTK_WINDOW (window), btn);\n"
            "  gtk_window_present (GTK_WINDOW (window));\n"
            "}\n\n"
            "int\nmain (int argc, char **argv)\n{\n"
            "  GtkApplication *app = gtk_application_new (\"" +
            app_id(info) +
            "\", G_APPLICATION_DEFAULT_FLAGS);\n"
            "  g_signal_connect (app, \"activate\", G_CALLBACK (activate), NULL);\n"
            "  return g_application_run (G_APPLICATION (app), argc, argv);\n"
            "}\n");
    add_gui_meta(files, info, "GtkShortcutsWindow sample.");
  } else if (tid == "gtk4-sourceview") {
    gtk_c(false, true, "#include <gtksourceview/gtksource.h>\n",
          "  GtkWidget *window = gtk_application_window_new (app);\n"
          "  gtk_window_set_title (GTK_WINDOW (window), \"" +
              n +
              "\");\n"
              "  gtk_window_set_default_size (GTK_WINDOW (window), 720, 520);\n"
              "  GtkSourceBuffer *buffer = gtk_source_buffer_new (NULL);\n"
              "  gtk_text_buffer_set_text (GTK_TEXT_BUFFER (buffer), \"// Start coding\\n\", -1);\n"
              "  GtkWidget *view = gtk_source_view_new_with_buffer (buffer);\n"
              "  gtk_source_view_set_show_line_numbers (GTK_SOURCE_VIEW (view), TRUE);\n"
              "  GtkWidget *scroll = gtk_scrolled_window_new ();\n"
              "  gtk_scrolled_window_set_child (GTK_SCROLLED_WINDOW (scroll), view);\n"
              "  gtk_window_set_child (GTK_WINDOW (window), scroll);\n"
              "  gtk_window_present (GTK_WINDOW (window));\n",
          "GtkSourceView 5 editor shell.");
  } else if (tid == "gtk4-columnview") {
    gtk_c(false, false, "",
          "  GtkWidget *window = gtk_application_window_new (app);\n"
          "  gtk_window_set_title (GTK_WINDOW (window), \"" +
              n +
              "\");\n"
              "  gtk_window_set_default_size (GTK_WINDOW (window), 480, 360);\n"
              "  GtkWidget *list = gtk_list_box_new ();\n"
              "  gtk_list_box_append (GTK_LIST_BOX (list), gtk_label_new (\"Item 1\"));\n"
              "  gtk_list_box_append (GTK_LIST_BOX (list), gtk_label_new (\"Item 2\"));\n"
              "  gtk_list_box_append (GTK_LIST_BOX (list), gtk_label_new (\"Item 3\"));\n"
              "  gtk_window_set_child (GTK_WINDOW (window), list);\n"
              "  gtk_window_present (GTK_WINDOW (window));\n",
          "List / column-style starter.");
  } else if (tid == "gtk4-dnd") {
    files.emplace_back("meson.build", meson_exec(info, "c", "src/main.c", {"gtk4"}));
    files.emplace_back(
        "src/main.c",
        "#include <gtk/gtk.h>\n\n"
        "static gboolean\non_drop (GtkDropTarget *target, const GValue *value, double x, double y, gpointer label)\n{\n"
        "  (void) target; (void) x; (void) y;\n"
        "  if (G_VALUE_HOLDS (value, G_TYPE_FILE))\n"
        "    {\n"
        "      GFile *file = g_value_get_object (value);\n"
        "      g_autofree char *path = g_file_get_path (file);\n"
        "      gtk_label_set_text (GTK_LABEL (label), path ? path : \"(dropped)\");\n"
        "      return TRUE;\n"
        "    }\n"
        "  return FALSE;\n"
        "}\n\n"
        "static void\nactivate (GtkApplication *app, gpointer user_data)\n{\n"
        "  (void) user_data;\n"
        "  GtkWidget *window = gtk_application_window_new (app);\n"
        "  gtk_window_set_title (GTK_WINDOW (window), \"" +
            n +
            "\");\n"
            "  gtk_window_set_default_size (GTK_WINDOW (window), 480, 320);\n"
            "  GtkWidget *label = gtk_label_new (\"Drop a file here\");\n"
            "  GtkDropTarget *target = gtk_drop_target_new (G_TYPE_FILE, GDK_ACTION_COPY);\n"
            "  g_signal_connect (target, \"drop\", G_CALLBACK (on_drop), label);\n"
            "  gtk_widget_add_controller (label, GTK_EVENT_CONTROLLER (target));\n"
            "  gtk_window_set_child (GTK_WINDOW (window), label);\n"
            "  gtk_window_present (GTK_WINDOW (window));\n"
            "}\n\n"
            "int\nmain (int argc, char **argv)\n{\n"
            "  GtkApplication *app = gtk_application_new (\"" +
            app_id(info) +
            "\", G_APPLICATION_DEFAULT_FLAGS);\n"
            "  g_signal_connect (app, \"activate\", G_CALLBACK (activate), NULL);\n"
            "  return g_application_run (G_APPLICATION (app), argc, argv);\n"
            "}\n");
    add_gui_meta(files, info, "Drag-and-drop file target.");
  } else if (tid == "gtk4-grid") {
    gtk_c(false, false, "",
          "  GtkWidget *window = gtk_application_window_new (app);\n"
          "  gtk_window_set_title (GTK_WINDOW (window), \"" +
              n +
              "\");\n"
              "  GtkWidget *grid = gtk_grid_new ();\n"
              "  gtk_grid_set_row_spacing (GTK_GRID (grid), 8);\n"
              "  gtk_grid_set_column_spacing (GTK_GRID (grid), 8);\n"
              "  gtk_widget_set_margin_top (grid, 16);\n"
              "  gtk_widget_set_margin_start (grid, 16);\n"
              "  for (int r = 0; r < 2; r++)\n"
              "    for (int c = 0; c < 3; c++)\n"
              "      {\n"
              "        g_autofree char *t = g_strdup_printf (\"%d,%d\", r, c);\n"
              "        gtk_grid_attach (GTK_GRID (grid), gtk_button_new_with_label (t), c, r, 1, 1);\n"
              "      }\n"
              "  gtk_window_set_child (GTK_WINDOW (window), grid);\n"
              "  gtk_window_present (GTK_WINDOW (window));\n",
          "GtkGrid layout sample.");
  } else if (tid == "gtk4-progress") {
    gtk_c(false, false, "",
          "  GtkWidget *window = gtk_application_window_new (app);\n"
          "  gtk_window_set_title (GTK_WINDOW (window), \"" +
              n +
              "\");\n"
              "  gtk_window_set_default_size (GTK_WINDOW (window), 420, 160);\n"
              "  GtkWidget *bar = gtk_progress_bar_new ();\n"
              "  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (bar), \"Working…\");\n"
              "  gtk_progress_bar_set_show_text (GTK_PROGRESS_BAR (bar), TRUE);\n"
              "  gtk_progress_bar_pulse (GTK_PROGRESS_BAR (bar));\n"
              "  gtk_widget_set_valign (bar, GTK_ALIGN_CENTER);\n"
              "  gtk_widget_set_margin_start (bar, 24);\n"
              "  gtk_widget_set_margin_end (bar, 24);\n"
              "  gtk_window_set_child (GTK_WINDOW (window), bar);\n"
              "  gtk_window_present (GTK_WINDOW (window));\n",
          "Progress bar sample.");
  } else if (tid == "console-c") {
    files.emplace_back("meson.build", meson_exec(info, "c", "src/main.c", {}));
    files.emplace_back("src/main.c",
                       "#include <stdio.h>\nint main(void){ puts(\"Hello from " + n +
                           "\"); return 0; }\n");
    files.emplace_back("README.md", readme(n, "Plain C console app.", meson_hint(info)));
  } else if (tid == "console-cpp") {
    files.emplace_back("meson.build", meson_exec(info, "cpp", "src/main.cpp", {}));
    files.emplace_back("src/main.cpp",
                       "#include <iostream>\nint main(){ std::cout<<\"Hello from " + n +
                           "\\n\"; return 0; }\n");
    files.emplace_back("README.md", readme(n, "Plain C++ console app.", meson_hint(info)));
  } else if (tid == "cli-goption") {
    files.emplace_back("meson.build",
                       meson_exec(info, "c", "src/main.c", {"gio-2.0"}));
    files.emplace_back(
        "src/main.c",
        "#include <gio/gio.h>\n#include <stdio.h>\n\n"
        "int\nmain (int argc, char **argv)\n{\n"
        "  gboolean verbose = FALSE;\n"
        "  gchar *name = NULL;\n"
        "  GOptionEntry entries[] = {\n"
        "    { \"verbose\", 'v', 0, G_OPTION_ARG_NONE, &verbose, \"Verbose output\", NULL },\n"
        "    { \"name\", 'n', 0, G_OPTION_ARG_STRING, &name, \"Name to greet\", \"NAME\" },\n"
        "    { NULL }\n"
        "  };\n"
        "  g_autoptr (GError) error = NULL;\n"
        "  g_autoptr (GOptionContext) ctx = g_option_context_new (\"- demo CLI\");\n"
        "  g_option_context_add_main_entries (ctx, entries, NULL);\n"
        "  if (!g_option_context_parse (ctx, &argc, &argv, &error))\n"
        "    {\n"
        "      g_printerr (\"%s\\n\", error->message);\n"
        "      return 1;\n"
        "    }\n"
        "  printf (\"Hello, %s!%s\\n\", name ? name : \"world\", verbose ? \" (verbose)\" : \"\");\n"
        "  g_free (name);\n"
        "  return 0;\n"
        "}\n");
    files.emplace_back("README.md",
                       readme(n, "GLib GOption CLI sample.", meson_hint(info)));
  } else if (tid == "shared-lib-c") {
    files.emplace_back("meson.build",
                       "project('" + n +
                           "', 'c', version: '0.1.0', meson_version: '>= 1.0.0')\n"
                           "inc = include_directories('src')\n"
                           "lib = library('" +
                           n +
                           "', 'src/lib.c', include_directories: inc, install: true)\n"
                           "executable('" +
                           n +
                           "-demo', 'src/main.c', include_directories: inc, link_with: lib, install: true)\n");
    files.emplace_back("src/lib.h",
                       "#pragma once\nconst char *" +
                           GabProjectTemplates::sanitize_app_id(n) + "_greet(void);\n");
    files.emplace_back("src/lib.c",
                       "#include \"lib.h\"\nconst char *" +
                           GabProjectTemplates::sanitize_app_id(n) +
                           "_greet(void){ return \"hello from lib\"; }\n");
    files.emplace_back("src/main.c",
                       "#include <stdio.h>\n#include \"lib.h\"\nint main(void){ puts(" +
                           GabProjectTemplates::sanitize_app_id(n) +
                           "_greet()); return 0; }\n");
    files.emplace_back("README.md",
                       readme(n, "Shared library + demo executable.",
                              "meson setup build && meson compile -C build && ./build/" + n +
                                  "-demo"));
  } else if (tid == "static-lib-cpp") {
    files.emplace_back("meson.build",
                       "project('" + n +
                           "', 'cpp', version: '0.1.0', default_options: ['cpp_std=c++17'])\n"
                           "inc = include_directories('src')\n"
                           "lib = static_library('" +
                           n +
                           "', 'src/lib.cpp', include_directories: inc)\n"
                           "executable('" +
                           n +
                           "', 'src/main.cpp', include_directories: inc, link_with: lib, install: true)\n");
    files.emplace_back("src/lib.hpp", "#pragma once\nnamespace demo { const char *greet(); }\n");
    files.emplace_back("src/lib.cpp",
                       "#include \"lib.hpp\"\nnamespace demo { const char *greet(){ return \"hello from static lib\"; } }\n");
    files.emplace_back("src/main.cpp",
                       "#include <iostream>\n#include \"lib.hpp\"\nint main(){ std::cout<<demo::greet()<<\"\\n\"; }\n");
    files.emplace_back("README.md",
                       readme(n, "Static C++ library + demo.", meson_hint(info)));
  } else if (tid == "cmake-gtk4") {
    files.emplace_back("CMakeLists.txt",
                       "cmake_minimum_required(VERSION 3.20)\nproject(" + n +
                           " C)\nfind_package(PkgConfig REQUIRED)\n"
                           "pkg_check_modules(GTK4 REQUIRED IMPORTED_TARGET gtk4)\n"
                           "add_executable(" +
                           n + " src/main.c)\ntarget_link_libraries(" + n +
                           " PRIVATE PkgConfig::GTK4)\n");
    files.emplace_back("src/main.c",
                       "#include <gtk/gtk.h>\n"
                       "static void activate(GtkApplication *app, gpointer){\n"
                       "  GtkWidget *w=gtk_application_window_new(app);\n"
                       "  gtk_window_set_title(GTK_WINDOW(w),\"" +
                           n +
                           "\");\n"
                           "  gtk_window_set_child(GTK_WINDOW(w), gtk_label_new(\"Hello from CMake\"));\n"
                           "  gtk_window_present(GTK_WINDOW(w));\n}\n"
                           "int main(int argc,char **argv){\n"
                           "  GtkApplication *app=gtk_application_new(\"" +
                           app_id(info) +
                           "\",G_APPLICATION_DEFAULT_FLAGS);\n"
                           "  g_signal_connect(app,\"activate\",G_CALLBACK(activate),NULL);\n"
                           "  return g_application_run(G_APPLICATION(app),argc,argv);\n}\n");
    /* Fix: C doesn't allow gpointer without name in that form for unused - use user_data */
    files.pop_back();
    files.emplace_back(
        "src/main.c",
        "#include <gtk/gtk.h>\n"
        "static void activate(GtkApplication *app, gpointer user_data){\n"
        "  (void)user_data;\n"
        "  GtkWidget *w=gtk_application_window_new(app);\n"
        "  gtk_window_set_title(GTK_WINDOW(w),\"" +
            n +
            "\");\n"
            "  gtk_window_set_child(GTK_WINDOW(w), gtk_label_new(\"Hello from CMake\"));\n"
            "  gtk_window_present(GTK_WINDOW(w));\n}\n"
            "int main(int argc,char **argv){\n"
            "  GtkApplication *app=gtk_application_new(\"" +
            app_id(info) +
            "\",G_APPLICATION_DEFAULT_FLAGS);\n"
            "  g_signal_connect(app,\"activate\",G_CALLBACK(activate),NULL);\n"
            "  return g_application_run(G_APPLICATION(app),argc,argv);\n}\n");
    files.emplace_back("data/" + n + ".desktop", desktop(info));
    files.emplace_back("README.md", readme(n, "GTK4 hello world using CMake.", cmake_hint(info)));
  } else if (tid == "cmake-console-cpp") {
    files.emplace_back("CMakeLists.txt",
                       "cmake_minimum_required(VERSION 3.20)\nproject(" + n +
                           " CXX)\nset(CMAKE_CXX_STANDARD 17)\nadd_executable(" + n +
                           " src/main.cpp)\n");
    files.emplace_back("src/main.cpp",
                       "#include <iostream>\nint main(){ std::cout<<\"Hello from " + n +
                           "\\n\"; }\n");
    files.emplace_back("README.md",
                       readme(n, "CMake C++ console starter.", cmake_hint(info)));
  } else if (tid == "empty-meson-c") {
    files.emplace_back("meson.build", meson_exec(info, "c", "src/main.c", {}));
    files.emplace_back("src/main.c", "int main(void){ return 0; }\n");
    files.emplace_back("README.md", readme(n, "Empty Meson C skeleton.", meson_hint(info)));
  } else if (tid == "empty-meson-cpp") {
    files.emplace_back("meson.build", meson_exec(info, "cpp", "src/main.cpp", {}));
    files.emplace_back("src/main.cpp", "int main(){ return 0; }\n");
    files.emplace_back("README.md", readme(n, "Empty Meson C++ skeleton.", meson_hint(info)));
  } else if (tid == "python-gi") {
    files.emplace_back("meson.build",
                       "project('" + n +
                           "', version: '0.1.0')\n"
                           "install_data('src/" +
                           n +
                           ".py', install_dir: get_option('bindir'), rename: '" + n +
                           "')\n");
    files.emplace_back("src/" + n + ".py",
                       "#!/usr/bin/env python3\n"
                       "import gi\n"
                       "gi.require_version('Gtk', '4.0')\n"
                       "from gi.repository import Gtk, Gio\n\n"
                       "class App(Gtk.Application):\n"
                       "    def __init__(self):\n"
                       "        super().__init__(application_id='" +
                           app_id(info) +
                           "')\n"
                           "    def do_activate(self):\n"
                           "        win = Gtk.ApplicationWindow(application=self, title='" +
                           n +
                           "')\n"
                           "        win.set_default_size(480, 320)\n"
                           "        win.set_child(Gtk.Label(label='Hello from Python + GTK4'))\n"
                           "        win.present()\n\n"
                           "if __name__ == '__main__':\n"
                           "    raise SystemExit(App().run())\n");
    /* Fix python - do_activate indentation wrong. Rewrite properly. */
    files.pop_back();
    files.emplace_back(
        "src/" + n + ".py",
        "#!/usr/bin/env python3\n"
        "import gi\n"
        "gi.require_version('Gtk', '4.0')\n"
        "from gi.repository import Gtk\n\n"
        "class App(Gtk.Application):\n"
        "    def __init__(self):\n"
        "        super().__init__(application_id='" +
            app_id(info) +
            "')\n\n"
            "    def do_activate(self):\n"
            "        win = Gtk.ApplicationWindow(application=self, title='" +
            n +
            "')\n"
            "        win.set_default_size(480, 320)\n"
            "        win.set_child(Gtk.Label(label='Hello from Python + GTK4'))\n"
            "        win.present()\n\n"
            "if __name__ == '__main__':\n"
            "    raise SystemExit(App().run())\n");
    files.emplace_back("README.md",
                       readme(n, "PyGObject GTK4 window.\n\nRun directly:\n```bash\npython3 src/" +
                                     n + ".py\n```",
                              "python3 src/" + n + ".py"));
  } else {
    error = "Unknown template: " + info.template_id;
    return false;
  }

  return write_tree(info.path, files, error);
}
